version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/flask-app
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 180
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 180
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 180
      runas: ec2-user

  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 180
      runas: ec2-user
