version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Zipping app..."
      - zip -r app.zip app.py requirements.txt

artifacts:
  files:
    - app.zip
    - requirements.txt
    - buildspec-test.yml       # ✅ include this explicitly
    - test         # optional: include tests if needed
  discard-paths: yes
